<?
$PERM["admin"]["7"]="R";
$PERM["admin"]["6"]="R";
$PERM["admin"]["*"]="D";
$PERM["admin"]["8"]="R";
$PERM["admin"]["10"]="R";
$PERM["admin"]["11"]="R";
$PERM["admin"]["13"]="R";
$PERM["wizards"]["*"]="D";
?>