<?php

use \Bitrix\Main\Localization\Loc;
use \Bitrix\Main\Application;

Loc::loadMessages(__FILE__);

class isys_bxe extends CModule
{
    var $MODULE_ID = "isys.bxe";
    var $MODULE_VERSION;
    var $MODULE_VERSION_DATE;
    var $MODULE_NAME;
    var $MODULE_DESCRIPTION;
    var $MODULE_CSS;
    var $MODULE_GROUP_RIGHTS = "Y";

    function __construct()
    {
        $arModuleVersion = array();
        include(__DIR__ . "/version.php");

        $this->MODULE_ID = 'isys.bxe';
        $this->MODULE_VERSION = $arModuleVersion["VERSION"];
        $this->MODULE_VERSION_DATE = $arModuleVersion["VERSION_DATE"];
        $this->MODULE_NAME = Loc::getMessage("ISYS_BXE_MODULE_NAME");
        $this->MODULE_DESCRIPTION = Loc::getMessage("ISYS_BXE_MODULE_DESC");

        $this->PARTNER_NAME = 'I-SYS';
        $this->PARTNER_URI = 'http://i-sys.ru';

        $this->PARTNER_NAME = Loc::getMessage('ISYS_PARTNER_NAME');
        $this->PARTNER_URI = Loc::getMessage('ISYS_PARTNER_URI');

        $this->MODULE_SORT = 1;
    }

    //Определяем место размещения модуля
    public function GetModuleRootPath($notDocumentRoot = false)
    {
        $dirname = str_replace("\\", "/", dirname(__DIR__));
        if ($notDocumentRoot) {
            return str_ireplace(Application::getDocumentRoot(), '', $dirname);
        } else {
            return $dirname;
        }
    }

    function InstallEvents()
    {
        //Вывод кнопки по событию OnAdminListDisplay
        $eventManager = \Bitrix\Main\EventManager::getInstance();
        $eventManager->registerEventHandler('main', 'OnAdminListDisplay', $this->MODULE_ID, '\ISYS\BXE\EventHandlers', 'AdminListDisplay', 100, '');
        $eventManager->registerEventHandler('main', 'OnAdminContextMenuShow', $this->MODULE_ID, '\ISYS\BXE\EventHandlers', 'AdminContextMenuShow', 100, '');
    }

    function UnInstallEvents()
    {
        $eventManager = \Bitrix\Main\EventManager::getInstance();
        $eventManager->unRegisterEventHandler('main', 'OnAdminListDisplay', $this->MODULE_ID, '\ISYS\BXE\EventHandlers', 'AdminListDisplay', 100, '');
        $eventManager->unRegisterEventHandler('main', 'OnAdminContextMenuShow', $this->MODULE_ID, '\ISYS\BXE\EventHandlers', 'AdminContextMenuShow', 100, '');

        parent::UnInstallEvents(); // TODO: Change the autogenerated stub
    }

    public function DoInstall()
    {
        global $APPLICATION;

        if (version_compare(phpversion(), '5.6', '<')) {
            global $arErrors;
            $arErrors = Array();

            if (version_compare(phpversion(), '5.6', '<')) {
                $arErrors[] = Loc::getMessage('ISYS_BXE_PHP_VER_IS_LOW');
            }

            $APPLICATION->IncludeAdminFile(Loc::getMessage("ISYS_BXE_INSTALL_TITLE"), $this->GetModuleRootPath() . "/install/step_error.php");

            return false;
        }

        include_once(realpath(dirname(__FILE__) . '/../lib/helpers.php'));

        if (!\ISYS\BXE\Helpers::AllNeededPHPExtensionsAvailableCheck()) {
            global $arErrors;

            $arErrors = \ISYS\BXE\Helpers::GetErrors();

            $APPLICATION->IncludeAdminFile(Loc::getMessage("ISYS_BXE_INSTALL_TITLE"), $this->GetModuleRootPath() . "/install/step_error.php");

            return false;
        }

        \Bitrix\Main\ModuleManager::registerModule($this->MODULE_ID);
        $this->InstallEvents();
        $APPLICATION->IncludeAdminFile(Loc::getMessage("ISYS_BXE_INSTALL_TITLE"), $this->GetModuleRootPath() . "/install/step.php");
    }

    public function DoUninstall()
    {
        global $APPLICATION;

        $this->UnInstallEvents();
        \Bitrix\Main\ModuleManager::unRegisterModule($this->MODULE_ID);

        $APPLICATION->IncludeAdminFile(Loc::getMessage("ISYS_MODULE_UNINSTALL_TITLE"), $this->GetModuleRootPath() . "/install/unstep.php");
    }
}
